### ISSUE TITLE
Export

### ISSUE THREAD

**Issue by mochoteimoso** [TsaariII/minishell#15]
These should return an error e.g. :  export: `A-': not a valid identifier

Test  26: ❌ export A- 
mini exit code = ?
bash exit code = 1
mini error = ()               
bash error = ( not a valid identifier)

Test  30: ❌ export HELLO-=123 
mini exit code = ?
bash exit code = 1
mini error = ()
bash error = ( not a valid identifier)

Test  31: ❌ export = 
mini exit code = ?
bash exit code = 1
mini error = ()
bash error = ( not a valid identifier)

Test  32: ❌ export 123 
mini exit code = ?
bash exit code = 1
mini error = ()
bash error = ( not a valid identifier)

**Comment by TsaariII** [comment]
Added validation for name in export and check that we have only = sign
