### ISSUE TITLE
exit

### ISSUE THREAD

**Issue by mochoteimoso** [TsaariII/minishell#17]
Exit issues - apparently these should not print an error and the exit code for the second one should be 156

Test  46: ❌ exit +"100" 
mini exit code = 2
bash exit code = 100
mini error = (exit numeric argument required)
bash error = ()

Test  49: ❌ exit -"100" 
mini exit code = 2
bash exit code = 156
mini error = (exit needs to be numeric)
bash error = ()clear

**Comment by TsaariII** [comment]
Changed fd to 1
